name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PAT}}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: ${{secrets.DOCKER_USER}}/methylr-gh:latest