name: Sign Docker image
on:
 push:
#   branches: [ main ]
 pull_request:
 #  branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2      
      -
        name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PAT}}
      -
        name: docker content trust
        run: |
          docker trust key load ${{ secrets.DOCKER_PER_KEY }} --name methylr
          docker trust signer add --key ${{ secrets.DOCKER_PUB_KEY }} methylr docker.io/jd21/methylr-gh:latest
          docker trust sign docker.io/jd21/methylr-gh:latest      